#!/bin/bash

# while-menu-dialog: a menu driven system information program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "Cleaner utility" \
    --title "Menu" \
    --clear \
    --cancel-label "Exit" \
    --menu "Please select:" $HEIGHT $WIDTH 4 \
    "1" "Remove a build" \
    "2" "unmerge" \
    "3" "unmerge the dependencies" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
  dialog  --menu "Please select:" $HEIGHT $WIDTH 4 \
    "REMOVE1" "Remove CHEATERex" \
    "REMOVE2" "Remove Moon64" \
    "REMOVE3" "Remove Render96ex_alpha" \
 ;;
    2 )
      result=$(emerge --unmerge CHEATERex Moon64 sm64ex sm64ex-master Render96ex-alpha sm64ex-alo_star_road)
      ;;
    3 )
      if [[ $(id -u) -eq 0 ]]; then
        result=$(du -sh /home/* 2> /dev/null)
        display_result "Home Space Utilization (All Users)"
      else
        result=$(du -sh $HOME 2> /dev/null)
        display_result "Home Space Utilization ($USER)"
      fi
      ;;
  esac
done
Script que muestra un menú de diálogo


export

REMOVE1 )
      result=$(rm -rf /opt/builds/CHEATERex)
      ;;
esac 
done 
